### ISSUE TITLE
Change the texture of the frame

### ISSUE THREAD

**Issue by NoltoxGit** [WasteLand-Dev/CraftableInvFrames#4]
**Describe the solution you'd like**
Would it be possible to add a custom name to the item in the recipe? For example:
```yml
item-frames-glow: true
# Allows or disables whether the given or crafted frame is a glow_item_frame` item frame item.
item-frame-glow-texture: true/false
recipe:
  ==: org.bukkit.inventory.ItemStack
  v: 3337
  type: LINGERING_POTION
  meta:
    ==: ItemMeta
    meta-type: POTION
    potion-type: minecraft:invisibility

```

Thank you for your plugin,
~ Noltox ~
